
eureka:
  instance:
    hostname: w0 #指定主机地址
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true
    service-url:
              defaultZone: http://w1:8001/eureka/,http://w2:8002/eureka/ #配置注册中心地址，互相注册
server:
  port: 8000
spring:
  profiles: reg0
  application:
    name: regCenter
---
eureka:
  instance:
    hostname: w1 #指定主机地址
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true
    service-url:
              defaultZone: http://w0:8000/eureka/,http://w2:8002/eureka/
server:
  port: 8001
spring:
  profiles: reg1
  application:
    name: regCenter
---
eureka:
  instance:
    hostname: w2 #指定主机地址
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true
    service-url:
          defaultZone: http://w0:8000/eureka/,http://w1:8001/eureka/
server:
  port: 8002
spring:
  profiles: reg2
  application:
    name: regCenter


